# Generated by Django 4.1.7 on 2023-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_products_category_alter_products_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=600),
        ),
    ]
