# Generated by Django 4.1.7 on 2023-05-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_products_description_alter_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
